apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: frontend
          image: testapi.azurecr.io/test-frontend:v4
          imagePullPolicy: Always
          ports:
            - containerPort: 80 # Nginx mặc định chạy cổng 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  selector:
    app: frontend-app
  ports:
    - port: 80
      targetPort: 80
